spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your name
    password: your database passord
    url: your database url
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.bsdl: info
  file:
    name: log/blog-prod.log

server:
  port: 8081