spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your name
    password: your database passord
    url: your database url
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.bsdl: debug
  file:
    name: log/blog-dev.log


